apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ta-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "dev"
        - name: ERR_VERBOSE
          value: "true"
        - name: GCS_SENSOR_BUCKET
          value: thirst-alert-sensor-images
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: JWT_SECRET
        - name: MAILER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MAILER_CLIENT_ID
        - name: MAILER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MAILER_CLIENT_SECRET
        - name: MAILER_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MAILER_REFRESH_TOKEN
        - name: MAILER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MAILER_ACCESS_TOKEN
        - name: GCS_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: GCS_CREDENTIALS