apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend
images:
- name: europe-west1-docker.pkg.dev/thirst-alert/thirst-alert-be/backend
  newTag: v1.2.0-dev.5
patches:
  - path: 00-env.yaml