apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/backend
images:
- name: europe-west1-docker.pkg.dev/thirst-alert-app/thirst-alert-be/backend
  newTag: v1.3.0-dev.8
patches:
- path: 00-env.yaml
- target:
    kind: Ingress
    name: api-ingress
    namespace: ta-backend
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: api.dev.thirst-alert.com
    - op: replace
      path: /spec/rules/0/host
      value: api.dev.thirst-alert.com
